---
- name: "Install fonts"
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - fontawesome-fonts-all
    - jetbrains-mono-fonts-all
    - source-foundry-hack-fonts
  become: true
