---
- name: "Install chezmoi"
  ansible.builtin.dnf:
    name: chezmoi
    state: present
  become: true

- name: "Check if chezmoi is initialized"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.local/share/chezmoi"
    register: chezmoi_source

- name: "Initialize chezmoi"
  ansible.builtin.command:
    cmd: >
      chezmoi init --source {{ dotfiles_repo_root }}/chezmoi
  args:
    creates: "{{ dotfiles_repo_root }}/chezmoi"
